export const SIDE_BAR_WIDTH = 230;
export const SIDE_BAR_COLOR = "#262e38";
export const SIDE_BAR_TEXT_COLOR = "#B9B2B2";
export const SIDE_BAR_TEXT_COLOR_HOVER = "#FFFFFF";
export const APP_NAME = "YOUR NAME";
export const RED = "red";
export const GREEN = "green";
export const BORDER_RADIUS = 7;
export const CARDS_BACKGROUND ="#FFFFFF"
